"""Where sealed evidence actually rests.

`EvidenceStore` owns the encryption; this module owns the bytes after it. The
split exists because of a defect that no test could have caught:
`evidence_storage_dir` defaults to `./evidence_store`, a directory on the
application server. On Render — and on every other platform with an ephemeral
filesystem — that directory is wiped on each deploy and each restart.

So evidence of an assault was being encrypted correctly, stored carefully, and
deleted by the next `git push`. For a feature whose entire purpose is to
produce something that still exists weeks later in front of a court, that is
the most serious failure the subsystem can have, and it was invisible: uploads
returned 201, the media row persisted in Postgres, and only the bytes went
missing.

**Everything here handles ciphertext only.** `EvidenceStore` seals with
AES-256-GCM before calling a backend, so a storage provider — and anyone who
obtains its keys — holds bytes it cannot read. That is what makes putting
recordings of people in danger on third-party infrastructure defensible at
all, and it is why the encryption deliberately did not move down here with the
I/O.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Protocol

import httpx

logger = logging.getLogger(__name__)


class EvidenceBackendError(RuntimeError):
    """Raised when the underlying store refuses a read, write or delete."""


class BlobBackend(Protocol):
    """Opaque byte storage, keyed by an id the caller generates."""

    def put(self, key: str, blob: bytes) -> None: ...

    def get(self, key: str) -> bytes: ...

    def remove(self, key: str) -> None: ...

    @property
    def describe(self) -> str:
        """Short name for logs and `/status`. Never includes credentials."""
        ...


class LocalBlobBackend:
    """Files on the application server's own disk.

    Correct for a self-hosted deployment with a real volume, and the right
    default for development. **Wrong for any host with an ephemeral
    filesystem** — see the module docstring.
    """

    def __init__(self, directory: str) -> None:
        self._directory = Path(directory)

    @property
    def describe(self) -> str:
        return f"local:{self._directory}"

    def _path_for(self, key: str) -> Path:
        # Basename only: the key is generated by us, but treating it as
        # untrusted costs nothing and keeps a future caller from walking out
        # of the directory with one.
        return self._directory / f"{Path(key).name}.enc"

    def put(self, key: str, blob: bytes) -> None:
        try:
            self._directory.mkdir(parents=True, exist_ok=True)
            path = self._path_for(key)
            # Written to a temporary name and moved into place, so a crash
            # mid-write cannot leave a truncated file that later fails to
            # decrypt with no way to tell why.
            temporary = path.with_suffix(".part")
            temporary.write_bytes(blob)
            temporary.replace(path)
        except OSError as exc:
            raise EvidenceBackendError(f"Could not store evidence: {exc}") from exc

    def get(self, key: str) -> bytes:
        try:
            return self._path_for(key).read_bytes()
        except OSError as exc:
            raise EvidenceBackendError(f"Could not read evidence: {exc}") from exc

    def remove(self, key: str) -> None:
        try:
            self._path_for(key).unlink(missing_ok=True)
        except OSError as exc:
            logger.warning("Could not delete evidence %s: %s", key, exc)


class SupabaseBlobBackend:
    """Supabase Storage over HTTPS.

    Chosen because the project already runs Supabase for the events archive,
    so it adds no new vendor, no new bill and no new set of credentials — and
    its free tier covers a safety app's evidence volume comfortably.

    **The bucket must be private.** The blobs are ciphertext, so a public
    bucket would leak nothing readable, but a private one means an attacker
    needs the service key *and* the encryption key rather than a guessable
    URL and one of them. Retrieval still goes through this application's
    authenticated, ownership-checked endpoint; no signed URL is ever handed
    to a client.

    Uses the **secret (service_role) key**, never the publishable one. The
    publishable key is meant to be distributed to clients, and a bucket its
    holder could read would put every recording one leaked mobile build away
    from disclosure.
    """

    def __init__(
        self,
        *,
        url: str,
        service_key: str,
        bucket: str,
        timeout_seconds: float = 30.0,
    ) -> None:
        self._base = url.rstrip("/")
        self._key = service_key
        self._bucket = bucket
        # Generous next to the rest of the app: an evidence blob can be tens
        # of megabytes on a slow uplink, and a timeout here loses a recording
        # rather than delaying a page.
        self._timeout = timeout_seconds

    @property
    def describe(self) -> str:
        return f"supabase:{self._bucket}"

    def _object_url(self, key: str) -> str:
        return f"{self._base}/storage/v1/object/{self._bucket}/{Path(key).name}.enc"

    @property
    def _headers(self) -> dict[str, str]:
        return {
            "Authorization": f"Bearer {self._key}",
            "apikey": self._key,
        }

    def put(self, key: str, blob: bytes) -> None:
        try:
            response = httpx.post(
                self._object_url(key),
                content=blob,
                headers={
                    **self._headers,
                    # Ciphertext. Declared as a generic binary stream so no
                    # proxy attempts to sniff, transcode or inline it.
                    "Content-Type": "application/octet-stream",
                    # Refuse to silently overwrite: storage ids are fresh
                    # UUIDs, so a collision means something is wrong and
                    # clobbering would destroy the earlier recording.
                    "x-upsert": "false",
                },
                timeout=self._timeout,
            )
        except httpx.HTTPError as exc:
            raise EvidenceBackendError(f"Supabase was unreachable: {exc}") from exc

        if response.status_code >= 400:
            raise EvidenceBackendError(
                f"Supabase refused the upload ({response.status_code}): "
                f"{response.text[:200]}"
            )

    def get(self, key: str) -> bytes:
        try:
            response = httpx.get(
                self._object_url(key), headers=self._headers, timeout=self._timeout
            )
        except httpx.HTTPError as exc:
            raise EvidenceBackendError(f"Supabase was unreachable: {exc}") from exc

        if response.status_code >= 400:
            raise EvidenceBackendError(
                f"Supabase could not return the evidence ({response.status_code})"
            )
        return response.content

    def remove(self, key: str) -> None:
        try:
            response = httpx.request(
                "DELETE",
                self._object_url(key),
                headers=self._headers,
                timeout=self._timeout,
            )
            if response.status_code >= 400 and response.status_code != 404:
                logger.warning(
                    "Supabase refused to delete evidence %s (%s)",
                    key,
                    response.status_code,
                )
        except httpx.HTTPError as exc:
            # Deletion failing is a retention problem, not a correctness one.
            # It must never propagate: the caller is usually erasing an
            # account, and a storage hiccup must not block that.
            logger.warning("Could not delete evidence %s: %s", key, exc)


def build_backend(settings) -> BlobBackend:
    """Picks where evidence rests.

    Supabase when it is configured, local disk otherwise. Deliberately not the
    other way round: the local default is the one that loses data on a
    platform with an ephemeral filesystem, so a configured object store always
    wins over it.
    """
    if settings.evidence_supabase_configured:
        return SupabaseBlobBackend(
            url=settings.supabase_url,
            service_key=settings.supabase_secret_key,
            bucket=settings.evidence_bucket,
        )
    return LocalBlobBackend(settings.evidence_storage_dir)
