// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkcVJVzimXB10ceg0A8gM2ZCzrj0tBDiw',
    appId: '1:1050083589372:web:94043ca8ce8aed3eef6b79',
    messagingSenderId: '1050083589372',
    projectId: 'safeher-2a1f2',
    authDomain: 'safeher-2a1f2.firebaseapp.com',
    storageBucket: 'safeher-2a1f2.firebasestorage.app',
    measurementId: 'G-QQPJ2VJF1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Qvdntx7rUn_kHKBEPTRgDt__lBWS0C8',
    appId: '1:1050083589372:android:26800c672afa6e31ef6b79',
    messagingSenderId: '1050083589372',
    projectId: 'safeher-2a1f2',
    storageBucket: 'safeher-2a1f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPWSC35SsJPSRV456TdOalK88RSx7ZuDA',
    appId: '1:1050083589372:ios:8c1f998138d93fc6ef6b79',
    messagingSenderId: '1050083589372',
    projectId: 'safeher-2a1f2',
    storageBucket: 'safeher-2a1f2.firebasestorage.app',
    iosBundleId: 'io.github.akshayag.safeher',
  );

}